---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Simplino Service
  description: Simplino Service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
consumes:
- application/json
produces:
- application/json
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
paths:
  "/api/establishment/{establishmentId}":
    get:
      summary: Get a establishment data
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
        required: true
      - in: path
        name: establishmentId
        schema:
          type: string
        required: true
        description: UUID of the establishment to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/GetEstablishmentResponseDefinition"
        '422':
          description: Failed. Something went wrong.
        '401':
          $ref: '#/definitions/UnauthorizedError'
    put:
      summary: Update a new establishment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/definitions/PutEstablishmentRequestDefinition"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/_id"
        '422':
          description: Failed. Something went wrong.
    delete:
      summary: Delete a establishment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/DeleteEstablishmentResponseDefinition"
        '422':
          description: Failed. Something went wrong.
  "/api/establishment":
    post:
      summary: Insert a new establishment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/definitions/PostEstablishmentRequestDefinition"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/_id"
        '422':
          description: Failed. Something went wrong.
definitions:
  _id:
    properties:
      uuid:
        type: string
  GetEstablishmentResponseDefinition:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      coordinates:
        type: object
      time_per_person:
        type: string
      number_of_allowed:
        type: string
      type:
        type: string
      is_deleted:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
      __v:
        type: integer
  PostEstablishmentRequestDefinition:
    type: object
    properties:
      name:
        type: string
      coordinates:
        type: object
      time_per_person:
        type: string
      number_of_allowed:
        type: string
      type:
        type: string
  PutEstablishmentRequestDefinition:
    type: object
    properties:
      name:
        type: string
      coordinates:
        type: object
      time_per_person:
        type: string
      number_of_allowed:
        type: string
      type:
        type: string
  DeleteEstablishmentResponseDefinition:
    type: object
    properties:
      n:
        type: integer
      nModified:
        type: integer
      ok:
        type: integer
  UnauthorizedError:
    description: Authentication information is missing or invalid
    headers:
      WWW_Authenticate:
        schema:
          type: string